# Generated by Django 3.1.7 on 2022-03-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20220315_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemodel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='port',
            field=models.SmallIntegerField(null=True, verbose_name='端口号'),
        ),
    ]
