# Generated by Django 3.1.7 on 2022-05-22 18:14

import backend.utils.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_auto_20220315_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUseServiceModel',
            fields=[
                ('create_time', backend.utils.base.ModelDateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', backend.utils.base.ModelDateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_use', to='service.servicemodel', verbose_name='服务ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_use', to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '最近使用的服务',
                'verbose_name_plural': '最近使用的服务',
                'db_table': 'service_latest_use',
            },
        ),
    ]
