# Generated by Django 3.1.7 on 2022-03-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRoleModel',
            fields=[
                ('id', models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(0, 'tester'), (1, 'super_user'), (2, 'manager'), (3, 'admin')], default=0, unique=True, verbose_name='测试角色')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, unique=True, verbose_name='密码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='test_role', to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '测试角色账户',
                'verbose_name_plural': '测试角色账户',
                'db_table': 'test_role',
            },
        ),
    ]
