# Generated by Django 3.1.7 on 2022-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testrolemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='rank',
            field=models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级'), (3, '资深'), (4, '专家')], default=0, verbose_name='职级'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '测试'), (1, '开发'), (2, '产品'), (3, '行政'), (4, '客服'), (5, '薪酬'), (6, '管理员')], default=0, verbose_name='职位'),
        ),
    ]
